name: makeup
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.3
  dio: ^5.4.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  bloc: ^8.1.4
  go_router: ^13.2.4
  pretty_dio_logger: ^1.3.1
  sliding_up_panel: ^2.0.0+1
  hexcolor: ^3.0.1

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
